import {useEffect,useMemo,useState} from "react";
import {collection,getDocs} from "firebase/firestore";
import {AlertTriangle,ArrowRight,Bell,CalendarDays,ClipboardCheck,CreditCard,FileCheck2,ShieldAlert,UsersRound} from "lucide-react";
import {db} from "../firebase";
import {can,PERMISSIONS} from "../permissions";

export default function MyWork({staff,onNavigate}){
  const [data,setData]=useState({walkIns:[],appointments:[],quotes:[],policies:[],claims:[],serviceRequests:[],approvals:[]});
  useEffect(()=>{(async()=>{
    const safe=async n=>{try{return (await getDocs(collection(db,n))).docs.map(d=>({id:d.id,...d.data()}))}catch{return []}};
    const [walkIns,appointments,quotes,policies,claims,serviceRequests,approvals]=await Promise.all(["walkIns","appointments","quotes","policies","claims","serviceRequests","approvals"].map(safe));
    setData({walkIns,appointments,quotes,policies,claims,serviceRequests,approvals});
  })()},[]);

  const items=useMemo(()=>{
    const out=[];
    if(can(staff,PERMISSIONS.WALKIN_READ))data.walkIns.filter(x=>x.status==="waiting"||x.assignedTo===staff.id).forEach(x=>out.push({priority:x.priority==="urgent"?1:2,type:"Walk-in",title:x.displayName,detail:x.status==="waiting"?"Waiting in lobby":"Assigned to you",page:"Walk-ins",Icon:UsersRound}));
    if(can(staff,PERMISSIONS.APPOINTMENT_READ)){const today=new Date().toISOString().slice(0,10);data.appointments.filter(x=>x.date===today&&!["completed","cancelled"].includes(x.status)).forEach(x=>out.push({priority:2,type:"Appointment",title:x.customerName,detail:(x.time||"")+" • "+x.department,page:"Appointments",Icon:CalendarDays}))}
    if(can(staff,PERMISSIONS.UNDERWRITING_REVIEW))data.quotes.filter(x=>x.status==="submitted").forEach(x=>out.push({priority:2,type:"Underwriting",title:x.customerName,detail:"Application awaiting review",page:"Quotes & Applications",Icon:ClipboardCheck}));
    if(can(staff,PERMISSIONS.POLICY_RENEW)){const horizon=new Date();horizon.setDate(horizon.getDate()+30);const h=horizon.toISOString().slice(0,10);data.policies.filter(x=>x.status==="active"&&x.expirationDate&&x.expirationDate<=h).forEach(x=>out.push({priority:2,type:"Renewal",title:x.customerName,detail:x.policyNumber+" expires "+x.expirationDate,page:"Policies",Icon:FileCheck2}))}
    if(can(staff,PERMISSIONS.CLAIM_READ))data.claims.filter(x=>x.assignedTo===staff.id||(!x.assignedTo&&x.coverageStatus==="pending")).forEach(x=>out.push({priority:x.priority==="high"?1:2,type:"Claim",title:x.claimNumber,detail:x.assignedTo===staff.id?"Assigned to you":"Coverage decision pending",page:"Claims",Icon:ShieldAlert}));
    if(can(staff,PERMISSIONS.SERVICE_REQUEST_READ))data.serviceRequests.filter(x=>["submitted","in_review"].includes(x.status)).forEach(x=>out.push({priority:2,type:"Service request",title:x.customerName||x.type,detail:(x.type||"request").replaceAll("_"," "),page:"Customers",Icon:Bell}));
    if(can(staff,PERMISSIONS.APPROVAL_READ))data.approvals.filter(x=>x.status==="pending").forEach(x=>out.push({priority:1,type:"Approval",title:x.title||x.actionType,detail:x.summary||"Approval required",page:"Company",Icon:AlertTriangle}));
    return out.sort((a,b)=>a.priority-b.priority);
  },[data,staff]);

  const counts={urgent:items.filter(x=>x.priority===1).length,total:items.length,claims:items.filter(x=>x.type==="Claim").length,approvals:items.filter(x=>x.type==="Approval").length};
  return <section className="content">
    <div className="page-heading"><div><div className="eyebrow">PERSONAL OPERATIONS</div><h1>My Work</h1><p>Automatic work generated by live Sterling Mutual operations. No manual task system—only real items that already require action.</p></div></div>
    <div className="metric-grid"><article className="metric-card"><div className="metric-value">{counts.total}</div><div className="metric-label">Items requiring attention</div><div className="metric-sub">Across your accessible departments</div></article><article className="metric-card"><div className="metric-value">{counts.urgent}</div><div className="metric-label">Priority items</div><div className="metric-sub">Urgent or approval-sensitive</div></article><article className="metric-card"><div className="metric-value">{counts.claims}</div><div className="metric-label">Claims work</div><div className="metric-sub">Assigned or pending decisions</div></article><article className="metric-card"><div className="metric-value">{counts.approvals}</div><div className="metric-label">Approvals</div><div className="metric-sub">Management review</div></article></div>
    <div className="table-card work-center"><div className="table-toolbar"><strong>Attention queue</strong><span>{items.length} items</span></div>{items.length===0?<div className="empty-state"><ClipboardCheck size={30}/><h3>You're caught up.</h3><p>New operational items will appear automatically.</p></div>:<div className="work-list">{items.map((item,i)=><button key={i} onClick={()=>onNavigate?.(item.page)} className={item.priority===1?"priority":""}><div className="work-icon"><item.Icon size={17}/></div><div><strong>{item.title}</strong><span>{item.type} • {item.detail}</span></div><ArrowRight size={15}/></button>)}</div>}</div>
  </section>
}
