export const PERMISSIONS={
  CUSTOMER_READ:"customer.read",
  CUSTOMER_CREATE:"customer.create",
  CUSTOMER_UPDATE:"customer.update",
  CUSTOMER_ACCOUNT_MANAGE:"customer.account.manage",
  CUSTOMER_NOTES:"customer.notes",
  CUSTOMER_ALERTS:"customer.alerts",
  WALKIN_READ:"walkin.read",
  WALKIN_CREATE:"walkin.create",
  WALKIN_MANAGE:"walkin.manage",
  APPOINTMENT_READ:"appointment.read",
  APPOINTMENT_MANAGE:"appointment.manage",
  STAFF_READ:"staff.read",
  STAFF_MANAGE:"staff.manage",
  STAFF_PERMISSION_MANAGE:"staff.permission.manage",
  AUDIT_READ:"audit.read",
  QUOTE_READ:"quote.read",
  QUOTE_CREATE:"quote.create",
  QUOTE_UPDATE:"quote.update",
  QUOTE_SUBMIT:"quote.submit",
  UNDERWRITING_REVIEW:"underwriting.review",
  POLICY_READ:"policy.read",
  POLICY_ISSUE:"policy.issue",
  POLICY_UPDATE:"policy.update",
  POLICY_DELETE:"policy.delete",
  POLICY_ENDORSE:"policy.endorse",
  POLICY_RENEW:"policy.renew",
  ASSET_MANAGE:"asset.manage",
  CLAIM_READ:"claim.read",
  CLAIM_CREATE_FOR_CUSTOMER:"claim.createForCustomer",
  CLAIM_UPDATE:"claim.update",
  CLAIM_ASSIGN:"claim.assign",
  CLAIM_RESERVE:"claim.reserve",
  CLAIM_DECIDE:"claim.decide",
  CLAIM_SETTLE:"claim.settle",
  CLAIM_CLOSE:"claim.close",
  CLAIM_PAYMENT:"claim.payment",
  EVIDENCE_MANAGE:"claim.evidence",
  SIU_READ:"siu.read",
  SIU_REFER:"siu.refer",
  SIU_MANAGE:"siu.manage",
  BILLING_READ:"billing.read",
  BILLING_MANAGE:"billing.manage",
  FINANCE_READ:"finance.read",
  FINANCE_MANAGE:"finance.manage",
  DOCUMENT_READ:"document.read",
  DOCUMENT_MANAGE:"document.manage",
  SERVICE_REQUEST_READ:"serviceRequest.read",
  SERVICE_REQUEST_MANAGE:"serviceRequest.manage",
  APPROVAL_READ:"approval.read",
  APPROVAL_MANAGE:"approval.manage",
  ARCHIVE_READ:"archive.read",
  ARCHIVE_MANAGE:"archive.manage",
  ADMIN_READ:"admin.read",
  ADMIN_MANAGE:"admin.manage"
};

export const PERMISSION_GROUPS={
  "Customer Service":[PERMISSIONS.CUSTOMER_READ,PERMISSIONS.CUSTOMER_CREATE,PERMISSIONS.CUSTOMER_UPDATE,PERMISSIONS.CUSTOMER_ACCOUNT_MANAGE,PERMISSIONS.CUSTOMER_NOTES,PERMISSIONS.CUSTOMER_ALERTS],
  "Front Office":[PERMISSIONS.WALKIN_READ,PERMISSIONS.WALKIN_CREATE,PERMISSIONS.WALKIN_MANAGE,PERMISSIONS.APPOINTMENT_READ,PERMISSIONS.APPOINTMENT_MANAGE],
  "Sales & Underwriting":[PERMISSIONS.QUOTE_READ,PERMISSIONS.QUOTE_CREATE,PERMISSIONS.QUOTE_UPDATE,PERMISSIONS.QUOTE_SUBMIT,PERMISSIONS.UNDERWRITING_REVIEW],
  "Policies":[PERMISSIONS.POLICY_READ,PERMISSIONS.POLICY_ISSUE,PERMISSIONS.POLICY_UPDATE,PERMISSIONS.POLICY_DELETE,PERMISSIONS.POLICY_ENDORSE,PERMISSIONS.POLICY_RENEW,PERMISSIONS.ASSET_MANAGE],
  "Claims":[PERMISSIONS.CLAIM_READ,PERMISSIONS.CLAIM_CREATE_FOR_CUSTOMER,PERMISSIONS.CLAIM_UPDATE,PERMISSIONS.CLAIM_ASSIGN,PERMISSIONS.CLAIM_RESERVE,PERMISSIONS.CLAIM_DECIDE,PERMISSIONS.CLAIM_SETTLE,PERMISSIONS.CLAIM_CLOSE,PERMISSIONS.CLAIM_PAYMENT,PERMISSIONS.EVIDENCE_MANAGE],
  "SIU":[PERMISSIONS.SIU_READ,PERMISSIONS.SIU_REFER,PERMISSIONS.SIU_MANAGE],
  "Billing & Finance":[PERMISSIONS.BILLING_READ,PERMISSIONS.BILLING_MANAGE,PERMISSIONS.FINANCE_READ,PERMISSIONS.FINANCE_MANAGE],
  "Records & Service":[PERMISSIONS.DOCUMENT_READ,PERMISSIONS.DOCUMENT_MANAGE,PERMISSIONS.SERVICE_REQUEST_READ,PERMISSIONS.SERVICE_REQUEST_MANAGE,PERMISSIONS.APPROVAL_READ,PERMISSIONS.APPROVAL_MANAGE,PERMISSIONS.ARCHIVE_READ,PERMISSIONS.ARCHIVE_MANAGE],
  "Administration":[PERMISSIONS.STAFF_READ,PERMISSIONS.STAFF_MANAGE,PERMISSIONS.STAFF_PERMISSION_MANAGE,PERMISSIONS.AUDIT_READ,PERMISSIONS.ADMIN_READ,PERMISSIONS.ADMIN_MANAGE]
};

export const ROLE_PRESETS={
  founder:{label:"Founder / Chief Executive Officer",department:"Executive Office",permissions:["*"]},
  agent:{label:"Insurance Agent",department:"Sales",permissions:[
    PERMISSIONS.CUSTOMER_READ,PERMISSIONS.CUSTOMER_CREATE,PERMISSIONS.CUSTOMER_UPDATE,PERMISSIONS.CUSTOMER_ACCOUNT_MANAGE,PERMISSIONS.CUSTOMER_NOTES,PERMISSIONS.CUSTOMER_ALERTS,
    PERMISSIONS.WALKIN_READ,PERMISSIONS.WALKIN_CREATE,PERMISSIONS.WALKIN_MANAGE,PERMISSIONS.APPOINTMENT_READ,PERMISSIONS.APPOINTMENT_MANAGE,
    PERMISSIONS.QUOTE_READ,PERMISSIONS.QUOTE_CREATE,PERMISSIONS.QUOTE_UPDATE,PERMISSIONS.QUOTE_SUBMIT,
    PERMISSIONS.POLICY_READ,PERMISSIONS.POLICY_ENDORSE,PERMISSIONS.POLICY_RENEW,PERMISSIONS.ASSET_MANAGE,
    PERMISSIONS.CLAIM_CREATE_FOR_CUSTOMER,PERMISSIONS.DOCUMENT_READ,PERMISSIONS.SERVICE_REQUEST_READ,PERMISSIONS.SERVICE_REQUEST_MANAGE
  ]},
  underwriter:{label:"Underwriter",department:"Underwriting",permissions:[
    PERMISSIONS.CUSTOMER_READ,PERMISSIONS.CUSTOMER_NOTES,PERMISSIONS.QUOTE_READ,PERMISSIONS.QUOTE_UPDATE,PERMISSIONS.UNDERWRITING_REVIEW,
    PERMISSIONS.POLICY_READ,PERMISSIONS.POLICY_ISSUE,PERMISSIONS.POLICY_UPDATE,PERMISSIONS.POLICY_ENDORSE,PERMISSIONS.POLICY_RENEW,PERMISSIONS.APPROVAL_READ
  ]},
  adjuster:{label:"Claims Adjuster",department:"Claims",permissions:[
    PERMISSIONS.CUSTOMER_READ,PERMISSIONS.CUSTOMER_NOTES,PERMISSIONS.POLICY_READ,PERMISSIONS.CLAIM_READ,
    PERMISSIONS.CLAIM_CREATE_FOR_CUSTOMER,PERMISSIONS.CLAIM_UPDATE,PERMISSIONS.CLAIM_RESERVE,PERMISSIONS.CLAIM_PAYMENT,
    PERMISSIONS.CLAIM_DECIDE,PERMISSIONS.EVIDENCE_MANAGE,PERMISSIONS.SIU_REFER,PERMISSIONS.DOCUMENT_READ
  ]},
  claimsManager:{label:"Claims Manager",department:"Claims",permissions:[
    PERMISSIONS.CUSTOMER_READ,PERMISSIONS.CUSTOMER_NOTES,PERMISSIONS.POLICY_READ,PERMISSIONS.CLAIM_READ,
    PERMISSIONS.CLAIM_CREATE_FOR_CUSTOMER,PERMISSIONS.CLAIM_UPDATE,PERMISSIONS.CLAIM_ASSIGN,
    PERMISSIONS.CLAIM_RESERVE,PERMISSIONS.CLAIM_DECIDE,PERMISSIONS.CLAIM_SETTLE,PERMISSIONS.CLAIM_CLOSE,
    PERMISSIONS.CLAIM_PAYMENT,PERMISSIONS.EVIDENCE_MANAGE,PERMISSIONS.SIU_READ,PERMISSIONS.SIU_REFER,PERMISSIONS.APPROVAL_READ
  ]},
  siuInvestigator:{label:"SIU Investigator",department:"Special Investigations",permissions:[
    PERMISSIONS.CUSTOMER_READ,PERMISSIONS.POLICY_READ,PERMISSIONS.CLAIM_READ,
    PERMISSIONS.SIU_READ,PERMISSIONS.SIU_MANAGE,PERMISSIONS.EVIDENCE_MANAGE,PERMISSIONS.DOCUMENT_READ
  ]},
  billingSpecialist:{label:"Billing Specialist",department:"Billing",permissions:[
    PERMISSIONS.CUSTOMER_READ,PERMISSIONS.CUSTOMER_NOTES,PERMISSIONS.POLICY_READ,PERMISSIONS.BILLING_READ,PERMISSIONS.BILLING_MANAGE,PERMISSIONS.SERVICE_REQUEST_READ,PERMISSIONS.SERVICE_REQUEST_MANAGE
  ]},
  financeManager:{label:"Finance Manager",department:"Finance",permissions:[
    PERMISSIONS.BILLING_READ,PERMISSIONS.FINANCE_READ,PERMISSIONS.FINANCE_MANAGE,PERMISSIONS.CLAIM_READ,PERMISSIONS.POLICY_READ,PERMISSIONS.APPROVAL_READ
  ]},
  receptionist:{label:"Reception / Front Desk",department:"Front Office",permissions:[
    PERMISSIONS.CUSTOMER_READ,PERMISSIONS.CUSTOMER_CREATE,PERMISSIONS.WALKIN_READ,PERMISSIONS.WALKIN_CREATE,PERMISSIONS.WALKIN_MANAGE,
    PERMISSIONS.APPOINTMENT_READ,PERMISSIONS.APPOINTMENT_MANAGE
  ]},
  administrator:{label:"System Administrator",department:"Administration",permissions:[
    PERMISSIONS.STAFF_READ,PERMISSIONS.STAFF_MANAGE,PERMISSIONS.STAFF_PERMISSION_MANAGE,PERMISSIONS.AUDIT_READ,PERMISSIONS.ADMIN_READ,PERMISSIONS.ADMIN_MANAGE,
    PERMISSIONS.CUSTOMER_ACCOUNT_MANAGE,PERMISSIONS.POLICY_DELETE,PERMISSIONS.ARCHIVE_READ,PERMISSIONS.ARCHIVE_MANAGE,
    PERMISSIONS.APPROVAL_READ,PERMISSIONS.APPROVAL_MANAGE,PERMISSIONS.WALKIN_READ,PERMISSIONS.WALKIN_CREATE,PERMISSIONS.WALKIN_MANAGE,
    PERMISSIONS.APPOINTMENT_READ,PERMISSIONS.APPOINTMENT_MANAGE,PERMISSIONS.DOCUMENT_READ,PERMISSIONS.DOCUMENT_MANAGE
  ]}
};

export function can(staff,permission){
  if(!staff||staff.status!=="active") return false;
  return staff.permissions?.includes("*")||staff.permissions?.includes(permission);
}

export function effectivePermissions(role,individual=[]){
  const base=ROLE_PRESETS[role]?.permissions||[];
  if(base.includes("*"))return ["*"];
  return [...new Set([...base,...individual])];
}
